name: "⬇️ Issue during install"
description: Report an issue while downloading Cypress.
labels: ['topic: installation']
body:
  - type: markdown
    attributes:
      value: |
        Have a question?  👉 [Start a new discussion](https://github.com/cypress-io/cypress/discussions) 

        Before submitting the issue, please make sure you do the following:

        - Install the latest [Cypress version](https://on.cypress.io/changelog)
        - If behind a proxy, [configure it properly](https://on.cypress.io/proxy-configuration).
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: A description including screenshots, stack traces, DEBUG logs, etc. 👉 https://on.cypress.io/troubleshooting
      placeholder: Current behavior
    validations:
      required: true
  - type: textarea
    id: debug-logs
    attributes:
      label: Debug logs
      description: Include DEBUG logs setting [`DEBUG=cypress:*`](https://on.cypress.io/troubleshooting#Print-DEBUG-logs/). Include npm/yarn logs if applicable.
      placeholder: Debug logs
  - type: input
    id: version
    attributes:
      label: Cypress Version
      description: Run `cypress version` to see your current version. If possible, please update Cypress to the [latest version](https://on.cypress.io/changelog) first.
      placeholder: ex. 7.6.0
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      options:
        - npm
        - yarn
        - Direct download
        - pnpm
        - other
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      options:
        - Linux
        - Mac
        - Windows
        - other
    validations:
      required: true